# Generated by Django 4.2.9 on 2024-01-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='platform_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=32, unique=True, verbose_name='平台名称')),
                ('login_itf', models.CharField(max_length=128, verbose_name='登录接口')),
                ('username', models.CharField(max_length=128, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('headers', models.CharField(max_length=256, verbose_name='请求头')),
                ('auth_name', models.CharField(default='Authorization', max_length=128, verbose_name='认证字段名')),
                ('auth_value', models.CharField(max_length=128, verbose_name='认证字段值')),
            ],
            options={
                'db_table': 'platform_info',
            },
        ),
        migrations.CreateModel(
            name='platform_itf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_itf', models.CharField(max_length=128, verbose_name='后端请求数据接口')),
                ('platform_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_itf', to='index.platform_info', verbose_name='')),
            ],
            options={
                'db_table': 'platform_itf',
            },
        ),
        migrations.CreateModel(
            name='inspect_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspect_time', models.DateTimeField(auto_now_add=True, verbose_name='巡检时间')),
                ('inspect_result', models.CharField(max_length=256, verbose_name='巡检结果')),
                ('platform_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_info', to='index.platform_info')),
                ('platform_itf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_itf', to='index.platform_itf')),
            ],
            options={
                'db_table': 'inspect_record',
            },
        ),
    ]
