# Generated by Django 4.2.9 on 2024-01-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_info',
            name='auth_value',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='认证字段值'),
        ),
    ]
