# Generated by Django 4.2.9 on 2024-01-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_platform_info_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform_Inspect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inspect_type', models.IntegerField(verbose_name='0：页面，1：后端接口')),
                ('web_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='前端页面地址')),
                ('data_itf', models.CharField(blank=True, max_length=128, null=True, verbose_name='后端请求数据接口')),
                ('platform_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_inspect', to='index.platform_info')),
            ],
            options={
                'db_table': 'platform_inspect',
            },
        ),
        migrations.RemoveField(
            model_name='inspect_record',
            name='platform_itf',
        ),
        migrations.AlterField(
            model_name='inspect_record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='platform_itf',
        ),
        migrations.AddField(
            model_name='inspect_record',
            name='platform_inspect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='platform_inspect', to='index.platform_inspect'),
            preserve_default=False,
        ),
    ]
