# Generated by Django 4.2.9 on 2024-01-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_platform_inspect_remove_inspect_record_platform_itf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_inspect',
            name='platform_info',
            field=models.ForeignKey(blank=True, db_column='platform_info_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_inspect', to='index.platform_info'),
        ),
        migrations.RenameField(
            model_name='platform_inspect',
            old_name='platform_info',
            new_name='platform_info_id',
        ),
        migrations.RemoveField(
            model_name='inspect_record',
            name='platform_info',
        ),
        migrations.RemoveField(
            model_name='inspect_record',
            name='platform_inspect',
        ),
        migrations.AddField(
            model_name='inspect_record',
            name='platform_info_id',
            field=models.ForeignKey(blank=True, db_column='platform_info_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_info', to='index.platform_info'),
        ),
        migrations.AddField(
            model_name='inspect_record',
            name='platform_inspect_id',
            field=models.ForeignKey(blank=True, db_column='platform_inspect_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_inspect', to='index.platform_inspect'),
        ),
    ]
