# Generated by Django 4.2.9 on 2024-01-23 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_rename_platform_inspect_platform_inspect_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_info',
            name='login_url',
            field=models.URLField(blank=True, null=True, verbose_name='登录地址'),
        ),
        migrations.AlterField(
            model_name='inspect_record',
            name='platform_inspect_id',
            field=models.ForeignKey(blank=True, db_column='platform_inspect_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_inspect_item', to='index.platform_inspect_item'),
        ),
        migrations.AlterField(
            model_name='platform_inspect_item',
            name='platform_info_id',
            field=models.ForeignKey(blank=True, db_column='platform_info_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_inspect_item', to='index.platform_info'),
        ),
        migrations.AlterField(
            model_name='platform_inspect_item',
            name='web_url',
            field=models.URLField(blank=True, null=True, verbose_name='前端页面地址'),
        ),
    ]
