# Generated by Django 4.2.9 on 2024-01-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_platform_info_login_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform_info',
            old_name='login_url',
            new_name='login_html',
        ),
    ]
