# Generated by Django 4.2.9 on 2024-01-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_rename_login_url_platform_info_login_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_info',
            name='token_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='后端返回的token字段名'),
        ),
    ]
