# Generated by Django 4.2.9 on 2024-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_platform_info_token_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_info',
            name='auth_name',
            field=models.CharField(default='Authorization', max_length=128, verbose_name='前端认证字段名'),
        ),
        migrations.AlterField(
            model_name='platform_info',
            name='auth_value',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='前端认证字段值'),
        ),
    ]
