# Generated by Django 4.2.9 on 2024-01-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_platform_info_auth_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspect_record',
            name='inspect_message',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='巡检结果'),
        ),
    ]
