# Generated by Django 4.2.9 on 2024-01-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_inspect_record_inspect_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspect_record',
            old_name='inspect_message',
            new_name='response_message',
        ),
        migrations.RemoveField(
            model_name='inspect_record',
            name='inspect_result',
        ),
        migrations.AddField(
            model_name='inspect_record',
            name='response_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='巡检响应码'),
        ),
    ]
