# Generated by Django 4.2.9 on 2024-01-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_inspect_record_inspect_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspect_record',
            name='inspect_time',
            field=models.DateTimeField(auto_now=True, verbose_name='巡检时间'),
        ),
    ]
