# Generated by Django 4.2.9 on 2024-01-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_platform_info_auth_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sys_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('account', models.CharField(max_length=32, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.CharField(max_length=32, null=True, verbose_name='邮箱')),
                ('tel', models.CharField(max_length=32, null=True, verbose_name='电话号码')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
