# Generated by Django 4.2.9 on 2024-01-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_alter_sys_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_user',
            name='account',
            field=models.CharField(max_length=32, unique=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='tel',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
