# Generated by Django 4.2.9 on 2024-01-29 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_inspecttype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inspecttype',
            table='inspectType',
        ),
    ]
