# Generated by Django 4.2.9 on 2024-01-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_alter_inspecttype_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform_inspect_item',
            old_name='web_url',
            new_name='webUrl',
        ),
        migrations.RemoveField(
            model_name='platform_inspect_item',
            name='data_itf',
        ),
        migrations.AddField(
            model_name='platform_inspect_item',
            name='dataItf',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='数据接口'),
        ),
    ]
