# Generated by Django 4.2.9 on 2024-01-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_rename_web_url_platform_inspect_item_weburl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_info',
            name='enabled',
            field=models.IntegerField(default=1, verbose_name='是否可用,0不可以，1可用'),
        ),
    ]
