# Generated by Django 4.2.9 on 2024-01-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_alter_platform_info_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_inspect_item',
            name='enabled',
            field=models.IntegerField(default=1, verbose_name='是否可用,0不可以，1可用'),
        ),
    ]
