# Generated by Django 4.2.9 on 2024-01-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_platform_inspect_item_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_info',
            name='disabled_reason',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='不可用的原因'),
        ),
        migrations.AddField(
            model_name='platform_inspect_item',
            name='disabled_reason',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='不可用的原因'),
        ),
    ]
