# Generated by Django 4.2.9 on 2024-01-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_platform_info_disabled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_inspect_item',
            name='interval_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='告警间隔时间，单位(分钟)'),
        ),
    ]
