# Generated by Django 4.2.9 on 2024-01-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_platform_inspect_item_interval_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_inspect_item',
            name='request_method',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='请求方法'),
        ),
    ]
