# Generated by Django 4.2.9 on 2024-01-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_alter_platform_inspect_item_disabled_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_type_name', models.CharField(max_length=32, verbose_name='通知类型')),
            ],
        ),
        migrations.CreateModel(
            name='Notice_Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_email', models.CharField(blank=True, max_length=64, null=True, verbose_name='接收者邮箱')),
                ('webhook', models.CharField(blank=True, max_length=128, null=True, verbose_name='企业微信webhook地址')),
                ('notice_type_id', models.ForeignKey(blank=True, db_column='notice_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_type', to='index.notice_type')),
            ],
        ),
    ]
