# Generated by Django 4.2.9 on 2024-01-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_notice_type_notice_config'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice_config',
            table='notice_config',
        ),
        migrations.AlterModelTable(
            name='notice_type',
            table='notice_type',
        ),
    ]
