# Generated by Django 4.2.9 on 2024-01-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_alter_notice_config_table_alter_notice_type_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_info',
            name='interval_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通知间隔时间，单位(分钟)'),
        ),
        migrations.AlterField(
            model_name='platform_inspect_item',
            name='interval_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通知间隔时间，单位(分钟)'),
        ),
    ]
