# Generated by Django 4.2.9 on 2024-01-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_alter_platform_info_interval_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_info',
            name='last_notice_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上一次通知时间'),
        ),
        migrations.AddField(
            model_name='platform_inspect_item',
            name='last_notice_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上一次通知时间'),
        ),
    ]
