# Generated by Django 4.2.9 on 2024-01-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_platform_info_last_notice_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspect_record',
            name='response_message',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='巡检结果'),
        ),
    ]
