# Generated by Django 4.2.9 on 2024-01-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_alter_inspect_record_response_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspect_record',
            name='response_message',
            field=models.TextField(blank=True, null=True, verbose_name='巡检结果'),
        ),
    ]
