# Generated by Django 4.2.9 on 2024-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_alter_inspect_record_response_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_info',
            name='disabled_reason',
            field=models.TextField(blank=True, null=True, verbose_name='不可用的原因'),
        ),
        migrations.AlterField(
            model_name='platform_inspect_item',
            name='disabled_reason',
            field=models.TextField(blank=True, null=True, verbose_name='不可用的原因'),
        ),
    ]
