# Generated by Django 4.2.9 on 2024-01-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_alter_platform_info_disabled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_inspect_item',
            name='device_online_field',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备在线字段'),
        ),
        migrations.AddField(
            model_name='platform_inspect_item',
            name='device_online_value',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备在线判定值'),
        ),
    ]
