# Generated by Django 4.2.9 on 2024-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0041_platform_inspect_item_device_online_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_inspect_item',
            name='device_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备名称字段'),
        ),
    ]
