# Generated by Django 4.2.9 on 2024-02-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0043_notice_config_notice_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_inspect_item',
            name='ignore_devices',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='通知忽略设备(列表格式)'),
        ),
    ]
