# Generated by Django 4.2.9 on 2024-02-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0044_platform_inspect_item_ignore_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_info',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
    ]
