# Generated by Django 4.2.9 on 2024-02-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0052_platform_inspect_item_retry_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_inspect_item',
            name='platform_inspect_inspect_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='平台巡检项名称'),
        ),
    ]
