# Generated by Django 4.2.9 on 2024-04-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0053_platform_inspect_item_platform_inspect_inspect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_inspect_item',
            name='is_notice',
            field=models.IntegerField(default=1, verbose_name='是否告警时通知,0不通知，1通知'),
        ),
    ]
