# Generated by Django 4.2.9 on 2024-06-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0054_platform_inspect_item_is_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform_inspect_item',
            old_name='platform_inspect_inspect_name',
            new_name='platform_inspect_item_name',
        ),
    ]
